version: "3"

services:
  datadog-agent:
    image: datadog/agent:latest
    networks:
      - micronaut
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=xxxxxxxxxxxxxxx
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_TAGS=env:local, application:micronaut-metrics
      - DD_INTEGRATION_NETTY_ENABLED=true
    links:
      - micronaut-metrics1
      - micronaut-metrics2
      - micronaut-metrics3
    expose:
      - 8125
      - 8126
    ports:
      - 8126:8126
      - 8125:8125

  micronaut-metrics1:
    image: micronaut-metrics:latest
    environment:
      - DD_SERVICE_NAME=micronaut1
      - DD_AGENT_HOST=datadog-agent
      - DD_APM_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_INTEGRATION_NETTY_ENABLED=true
    networks:
      - micronaut
    expose:
      - 8181
    ports:
      - 8181:8181

  micronaut-metrics2:
    image: micronaut-metrics:latest
    environment:
      - DD_SERVICE_NAME=micronaut2
      - DD_AGENT_HOST=datadog-agent
      - DD_APM_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_INTEGRATION_NETTY_ENABLED=true
    networks:
      - micronaut
    expose:
      - 8282
    ports:
      - 8282:8181

  micronaut-metrics3:
    image: micronaut-metrics:latest
    environment:
      - DD_SERVICE_NAME=micronaut3
      - DD_AGENT_HOST=datadog-agent
      - DD_APM_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_INTEGRATION_NETTY_ENABLED=true
    networks:
      - micronaut
    expose:
      - 8383
    ports:
      - 8383:8181

networks:
  micronaut:
     driver: bridge